name: Deploy Graasp backend to development environment

# Controls when the action will run.
on:
  # Triggers the workflow on push events only for the main branch
  push:
    branches:
    - main

  # Triggers the workflow on closed pull request events only for the main branch
  pull_request:
    branches: [main]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-ecs-backend-workflow:
    # repository name
    name: Graasp
    # Reference reusable workflow file. Using the commit SHA is the safest for stability and security
    uses: graasp/graasp-deploy/.github/workflows/cintegration-ecs-backend.yml@5ad156f86b2de177a81546db2ddc252a2ace36ca
    # ecs-task-definition with template file. 
    with:
      ecs-task-definition: '.aws/graasp-dev.json'
    # required secrets
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      aws-region: ${{ secrets.AWS_REGION_DEV }}
      ecs-cluster: ${{ secrets.ECS_CLUSTER_GRAASP_DEV }}
      ecs-service: ${{ secrets.ECS_SERVICE_GRAASP_DEV }}
      ecr-repository: ${{ secrets.ECR_REPOSITORY_GRAASP_DEV }}
      container-name-graasp: ${{ secrets.CONTAINER_NAME_GRAASP_DEV }}
      container-name-iframely: ${{ secrets.CONTAINER_NAME_IFRAMELY_DEV }}
      container-name-classifier: ${{ secrets.CONTAINER_NAME_CLASSIFIER_DEV }}
      container-image-iframely: ${{ secrets.CONTAINER_IMAGE_IFRAMELY_DEV }}
      container-image-classifier: ${{ secrets.CONTAINER_IMAGE_CLASSIFIER_DEV }}
      apps-jwt-secret: ${{ secrets.APPS_JWT_SECRET_DEV }}
      apps-plugin: ${{ secrets.APPS_PLUGIN_DEV }}
      auth-client-host: ${{ secrets.AUTH_CLIENT_HOST_DEV }}
      auth-token-expiration-in-minutes: ${{ secrets.AUTH_TOKEN_EXPIRATION_IN_MINUTES_DEV }}
      auth-token-jwt-secret: ${{ secrets.AUTH_TOKEN_JWT_SECRET_DEV }}
      avatars-path-prefix: ${{ secrets.AVATARS_PATH_PREFIX_DEV }}
      chatbox-plugin: ${{ secrets.CHATBOX_PLUGIN_DEV }}
      client-host: ${{ secrets.CLIENT_HOST_DEV }}
      cookie-domain: ${{ secrets.COOKIE_DOMAIN_DEV }}
      cors-origin-regex: ${{ secrets.CORS_ORIGIN_REGEX_DEV }}
      database-logs: ${{ secrets.DATABASE_LOGS_DEV }}
      email-links-host: ${{ secrets.EMAIL_LINKS_HOST_DEV }}
      embedded-link-item-iframely-href-origin: ${{ secrets.EMBEDDED_LINK_ITEM_IFRAMELY_HREF_ORIGIN_DEV }}
      embedded-link-item-plugin: ${{ secrets.EMBEDDED_LINK_ITEM_PLUGIN_DEV }}
      file-storage-root-path: ${{ secrets.FILE_STORAGE_ROOT_PATH_DEV }}
      files-path-prefix: ${{ secrets.FILES_PATH_PREFIX_DEV }}
      hidden-tag-id: ${{ secrets.HIDDEN_TAG_ID_DEV }}
      hostname: ${{ secrets.HOSTNAME_DEV }}
      image-classifier-api: ${{ secrets.IMAGE_CLASSIFIER_API_DEV }}
      jwt-secret: ${{ secrets.JWT_SECRET_DEV }}
      login-item-tag-id: ${{ secrets.LOGIN_ITEM_TAG_ID_DEV }}
      mailer-config-from-email: ${{ secrets.MAILER_CONFIG_FROM_EMAIL_DEV }}
      mailer-config-password: ${{ secrets.MAILER_CONFIG_PASSWORD_DEV }}
      mailer-config-smtp-host: ${{ secrets.MAILER_CONFIG_SMTP_HOST_DEV }}
      mailer-config-username: ${{ secrets.MAILER_CONFIG_USERNAME_DEV }}
      node-env: ${{ secrets.NODE_ENV_DEV }}
      node-env-container-2: ${{ secrets.NODE_ENV_2_DEV }}
      pg-connection-uri: ${{ secrets.PG_CONNECTION_URI_DEV }}
      port: ${{ secrets.PORT_DEV }}
      public-plugin: ${{ secrets.PUBLIC_PLUGIN_DEV }}
      public-tag-id: ${{ secrets.PUBLIC_TAG_ID_DEV }}
      published-tag-id: ${{ secrets.PUBLISHED_TAG_ID_DEV }}
      redis-host: ${{ secrets.REDIS_HOST_DEV }}
      redis-port: ${{ secrets.REDIS_PORT_DEV }}
      redis-username: ${{ secrets.REDIS_USERNAME_DEV }}
      refresh-token-expiration-in-minutes: ${{ secrets.REFRESH_TOKEN_EXPIRATION_IN_MINUTES_DEV }}
      refresh-token-jwt-secret: ${{ secrets.REFRESH_TOKEN_JWT_SECRET_DEV }}
      roarr-log: ${{ secrets.ROARR_LOG_DEV }}
      s3-file-item-access-key-id: ${{ secrets.S3_FILE_ITEM_ACCESS_KEY_ID_DEV }}
      s3-file-item-bucket: ${{ secrets.S3_FILE_ITEM_BUCKET_DEV }}
      s3-file-item-access-plugin: ${{ secrets.S3_FILE_ITEM_PLUGIN_DEV }}
      s3-file-item-region: ${{ secrets.S3_FILE_ITEM_REGION_DEV }}
      s3-file-item-secret-access-key: ${{ secrets.S3_FILE_ITEM_SECRET_ACCESS_KEY_DEV }}
      save-actions: ${{ secrets.SAVE_ACTIONS_DEV }}
      secure-session-secret-key: ${{ secrets.SECURE_SESSION_SECRET_KEY_DEV }}
      thumbnails-path-prefix: ${{ secrets.THUMBNAILS_PATH_PREFIX_DEV }}
      token-based-auth: ${{ secrets.TOKEN_BASED_AUTH_DEV }}
      websockets-plugin: ${{ secrets.WEBSOCKETS_PLUGIN_DEV }}
